export const MODEL_IS_EMPTY = 1;
export const SITEMAP_DOMAIN_LOST = 2;

export const ARRAY_CONSTRAIN_FOR_NON_ARRAY_PROP = 3;
export const ARRAY_MIN_OR_MAX_CONSTRAIN_USED_WITH_LENGTH = 4;
export const ARRAY_MIN_GREATER_MAX_CONSTRAIN = 5;
export const ARRAY_LENGTH_CONSTRAIN_IS_NEGATIVE_OR_ZERO = 6;
export const ARRAY_LENGTH_CONSTRAIN_IS_NOT_INTEGER = 7;
export const ARRAY_MAX_CONSTRAIN_IS_NEGATIVE_OR_ZERO = 8;
export const ARRAY_MAX_CONSTRAIN_IS_NOT_INTEGER = 9;
export const ARRAY_CONSTRAINS_MAX_MIN_ARE_EQUAL = 10;
export const ARRAY_MIN_CONSTRAIN_IS_NEGATIVE_OR_ZERO = 11;
export const ARRAY_MIN_CONSTRAIN_IS_NOT_INTEGER = 12;
export const ARRAY_MIN_AND_OPTIONAL_ARE_USED = 13;

export const STRING_MIN_OR_MAX_CONSTRAIN_USED_WITH_LENGTH = 14;
export const STRING_CONSTRAINS_MAX_MIN_ARE_EQUAL = 15;
export const STRING_MIN_GREATER_MAX_CONSTRAIN = 16;
export const STRING_LOWERCASE_USED_WITH_UPPERCASE = 17;
export const STRING_MAX_CONSTRAIN_IS_NEGATIVE_OR_ZERO = 18;
export const STRING_MAX_CONSTRAIN_IS_NOT_INTEGER = 19;
export const STRING_MIN_CONSTRAIN_IS_NEGATIVE_OR_ZERO = 20;
export const STRING_MIN_CONSTRAIN_IS_NOT_INTEGER = 21;

export const FLOAT_CONSTRAINS_MAX_MIN_ARE_EQUAL = 22;
export const FLOAT_MIN_GREATER_MAX_CONSTRAIN = 23;
export const FLOAT_MAX_CONSTRAIN_IS_NEGATIVE_OR_ZERO = 24;
export const FLOAT_MAX_CONSTRAIN_IS_NOT_INTEGER = 25;
export const FLOAT_MIN_CONSTRAIN_IS_NEGATIVE_OR_ZERO = 26;
export const FLOAT_MIN_CONSTRAIN_IS_NOT_INTEGER = 27;

export const INT_CONSTRAINS_MAX_MIN_ARE_EQUAL = 28;
export const INT_MIN_GREATER_MAX_CONSTRAIN = 29;
export const INT_MAX_CONSTRAIN_IS_NEGATIVE_OR_ZERO = 30;
export const INT_MAX_CONSTRAIN_IS_NOT_INTEGER = 31;
export const INT_MIN_CONSTRAIN_IS_NEGATIVE_OR_ZERO = 32;
export const INT_MIN_CONSTRAIN_IS_NOT_INTEGER = 33;

export const SITEMAP_MODEL_CHANGEFREQ_WRONG = 34;
